name: drink
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pie_chart: ^5.4.0
  shared_preferences: ^2.5.3
  wave: ^0.2.2
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
  intl: ^0.20.2
  fl_chart: ^1.0.0
  android_intent_plus: ^5.3.0
  android_alarm_manager_plus: ^4.0.7
  flutter_timezone: ^4.1.1
  permission_handler: ^12.0.0+1
  workmanager: ^0.6.0
  overlay_support: ^2.1.0
  awesome_notifications: ^0.10.1
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  provider: ^6.1.5
  easy_localization: ^3.0.7+1
  file_picker: ^10.2.0
  flutter_launcher_icons: ^0.14.4
  google_fonts: ^6.2.1
  lottie: ^3.3.1
  audioplayers: ^6.5.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.13.0
  google_mobile_ads: ^6.0.0
  flutter_native_splash: ^2.4.6
  confetti: ^0.8.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/facebook.png
    - assets/google.png
    - assets/womandancing.png
    - assets/drop.png
    - assets/mandancing.png
    - assets/breastfeeding.png
    - assets/pregnant.png
    - assets/translations/
    - assets/lottie/cup.json
    - assets/lottie/water.json
    - assets/drink_icon.png
    - assets/water.mp3
    - assets/bell.mp3
    - assets/chime.mp3
    - assets/splash_text.json
   


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/drink_icon.png"


flutter_native_splash:
  color: "#1F1F2F"
  image: assets/splashing.png
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

  android_12:
    color: "#1F1F2F"
    icon_background_color: "#1F1F2F"
    image: assets/splashing.png
    


